// ********RoostGPT********
// Test generated by RoostGPT for test csharp-test using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using Core.Services;
using System;

namespace Core.Test
{
    [TestFixture]
    public class Homepage_17578ba839
    {
        private IAuth _rep;

        [SetUp]
        public void Setup()
        {
            // TODO: Initialize _rep with a mock object
        }

        [Test]
        public void Homepage_WhenCalledWithValidIAuthObject_SetsRepCorrectly()
        {
            // Arrange
            var sut = new Homepage(_rep);
            
            // Act
            var result = sut._rep;

            // Assert
            Assert.That(result, Is.EqualTo(_rep));
        }

        [Test]
        public void Homepage_WhenCalledWithNull_ThrowsArgumentNullException()
        {
            // Arrange
            IAuth nullRep = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new Homepage(nullRep));
        }
    }
}
