// ********RoostGPT********
// Test generated by RoostGPT for test csharp-test using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using Core.Services;
using System;
using NSubstitute;

namespace Core.Test
{
    public class Homepage_17578ba839
    {
        private IAuth _authMock;

        [SetUp]
        public void SetUp()
        {
            _authMock = Substitute.For<IAuth>();
        }

        [Test]
        public void Homepage_WhenCalledWithValidIAuthObject_InstanceIsCreated()
        {
            var homepage = new Homepage(_authMock);
            Assert.IsNotNull(homepage);
        }

        [Test]
        public void Homepage_WhenCalledWithNull_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new Homepage(null));
        }
    }
}
