// ********RoostGPT********
// Test generated by RoostGPT for test csharp-test using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using Core;
using NSubstitute;

namespace Core.Test
{
    public class Homepage_Homepage_17578ba839
    {
        private IAuth _auth;
        private Homepage _homepage;

        [SetUp]
        public void Setup()
        {
            _auth = Substitute.For<IAuth>();
            _homepage = new Homepage(_auth);
        }

        [Test]
        public void Homepage_Constructor_SuccessfullyInitializes()
        {
            Assert.That(_homepage, Is.Not.Null);
        }

        [Test]
        public void Homepage_Constructor_FailsWithNullAuth()
        {
            IAuth nullAuth = null;
            Assert.Throws<ArgumentNullException>(() => new Homepage(nullAuth));
        }
    }
}
