// ********RoostGPT********
// Test generated by RoostGPT for test csharp-test using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using Core;

// Assuming that NSubstitute and IAuth are part of the Core namespace
// If not, please replace 'Core' with the correct namespace

namespace Core.Test
{
    [TestFixture]
    public class HomepageTests
    {
        private IAuth _authMock;
        private Homepage _homepage;

        [SetUp]
        public void Setup()
        {
            _authMock = NSubstitute.Substitute.For<IAuth>();
            _homepage = new Homepage(_authMock);
        }

        [Test]
        public void Homepage_Constructor_Success()
        {
            Assert.That(_homepage, Is.Not.Null);
        }

        [Test]
        public void Homepage_Constructor_Failure()
        {
            Assert.Throws<System.ArgumentNullException>(() => new Homepage(null));
        }
    }
}
